### ISSUE TITLE
Error thrown when changing `audioOutput` on `TVIAudioController`

### ISSUE THREAD

**Issue by jnagel33** [twilio/video-quickstart-swift#220]
### Description

Changing `audioOutput` on `TVIAudioController` results in an error being logged:
ERROR:TwilioVideo:[Platform]:Failed to set webrtc configuration : The operation couldn’t be completed. (OSStatus error 560030580.)

### Steps to Reproduce

1. Connect to a room
2. Change `audioOutput` on `TVIAudioController` to either `.voiceChatSpeaker` or `.voiceChatDefault`
3. The audio output change does work but an error is logged in the console

#### Code

```swift
// Code that helps reproduce the issue
TVIAudioController.shared().audioOutput = TVIAudioOutput.voiceChatSpeaker
```

#### Reproduces How Often

100%

#### Logs

```
ERROR:TwilioVideo:[Platform]:Failed to set webrtc configuration : The operation couldn’t be completed. (OSStatus error 560030580.)
```

### Versions

 v1.3.10

#### Video iOS SDK

 v1.3.10

**Comment by piyushtank** [comment]
@jnagel33 Thanks for reaching out. I think the reason, why you are observing the error logs, is probably because the video SDK tries to set the preferred number of input/output channels when the AVAudioSession is not activated. We will try to fix this in future releases of 1.x, however, we should have this already fixed in our Video SDK 2.0 preview releases. Also we have improved Audio APIs on 2.0 to give more flexibilities to developers. I would recommend using our latest version of 2.0 preview SDK.

VideoSDK 2.0 preview9 change logs - https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x

Let me know if you have any questions.

**Comment by jnagel33** [comment]
@piyushtank Thanks for the response. We have tried using the VideoSDK 2.0 preview9 version but we were experiencing a more severe issue on that release. There is a common scenario where user doesn't receive disconnect events immediately when entering a room using CallKit.

Steps to reproduce:

- Accept an invite to join a room while on the lock screen(CallKit)
- Have the other remote participant disconnect from the room. The user that accepted the invite is doesn't receive any room delegate callbacks letting them know that the other user has disconnected until the call times out.

This is only an issue when the user accepts the call on the lock screen and doesn't navigate into the app while on the call. If they accept the call while not on the lock screen or navigate into the app from the lock screen then they receive the disconnect event as expected.

**Comment by piyushtank** [comment]
@jnagel33 Thanks for trying out 2.0.0-preview9 and reporting your observations. We will try out the scenario where a user receives an incoming call using CallKit when the phone is locked. 
I will update you soon with our findings.

**Comment by GuntisTreulands** [comment]
@jnagel33 Hi! On which iPhone devices (and what iOS versions) are you experiencing this issue? 

After accepting invite - are both participants able to hear each other? And then second participant presses disconnect button, and event is still not received on first device?

**Comment by jnagel33** [comment]
@GuntisTreulands I'm experiencing this on both of my devices iPhone X iOS 11.2.2 and iPad Air 2 iOS 11.2.1. 

After accepting the audio both participants are able to hear each other and call seems to function properly up until the disconnect. 

Correct, the disconnect event is not received on the first device(which is on the lock screen) when second participant disconnects.

**Comment by paynerc** [comment]
Hey @jnagel33,

I have been attempting to diagnose the issue that you reported regarding not receiving any delegate call backs from the lock screen when using CallKit.

I have tested this extensively and am not able to reproduce what you are seeing. When on the lock screen, and a participant disconnects, I am indeed getting the `func room(_ room: TVIRoom, participantDidDisconnect participant: TVIRemoteParticipant)` call back and the code therein executes.

Are you saying that you are not receiving that callback? 

Unlike a call model, TwilioVideo is room based, and you won't receive the `func room(_ room: TVIRoom, didDisconnectWithError error: Error?)` call back until all participants, including yourself, leave the room OR the room is ended via the REST API. 

I you are indeed expecting that callback, then that is your issue. In this case I would suggest putting your disconnection logic in the `func room(_ room: TVIRoom, participantDidDisconnect participant: TVIRemoteParticipant)` call back and when you are down to 0 remote participants, you can trigger code to clean up the call kit UI, etc.

Let me know if you have any further issues.

Ryan

**Comment by jnagel33** [comment]
I'm unable to reproduce this on 2.0.1. Closing
